@baseUrl = http://localhost:8080

GET {{baseUrl}}/customer

###

GET {{baseUrl}}/customer?query=john

###

POST {{baseUrl}}/customer
Content-Type: application/json

{
  "name": "Jack Marshal"
}

###

GET {{baseUrl}}/customer
