@baseUrl = http://localhost:8080

GET {{baseUrl}}/customer

###

GET {{baseUrl}}/customer?query=blue

###

GET {{baseUrl}}/customer?query=do

###

GET {{baseUrl}}/customer?query=r%bl

###

POST {{baseUrl}}/customer
Content-Type: application/json

{
  "name": "Mr Blue"
}

###

POST {{baseUrl}}/customer
Content-Type: application/json

{
