@baseUrl = http://localhost:8080

GET {{baseUrl}}/customer

###

GET {{baseUrl}}/customer?query=john

###

GET {{baseUrl}}/customer?query=do

###

GET {{baseUrl}}/customer?query=hn%20do

###

POST {{baseUrl}}/customer
Content-Type: application/json

{
  "name": "Jack Marshals"
}
