@baseUrl = http://localhost:8080

GET {{baseUrl}}/order

###

GET {{baseUrl}}/order/1

###

GET {{baseUrl}}/order/abc

###

POST {{baseUrl}}/order
Content-Type: application/json

{
  "description": "Test Order",
  "customer": {
    "id": 4
  }
}

###

GET {{baseUrl}}/order
