@baseUrl = http://localhost:8080

GET {{baseUrl}}/order

###

GET {{baseUrl}}/order?page=0&size=20&sort=id,asc


###

GET {{baseUrl}}/order?page=5&size=20&sort=id,asc

###

GET {{baseUrl}}/order?page=1&size=5&sort=id,desc

###

GET {{baseUrl}}/order?page=0&size=250

###

GET {{baseUrl}}/order/10004

###

GET {{baseUrl}}/order/abc

###

POST {{baseUrl}}/order
Content-Type: application/json

{
  "description": "Test Order",
  "customerId": 4,
  "productIds": [1]
}
