@baseUrl = http://localhost:8080

POST {{baseUrl}}/products
Content-Type: application/json

{
  "description": "Ballpoint pen"
}

###

GET {{baseUrl}}/products

###

GET {{baseUrl}}/products/3

###

GET {{baseUrl}}/products/abc

###

POST {{baseUrl}}/products
Content-Type: application/json

{
